install.packages("purrr")
devtools::check()
usethis::use_git()
usethis::use_git_remote(url="git@github.com:Henri-Bodet/packageTest.git"
                        )

usethis::edit_git_config()
usethis::use_testthat()
usethis::use_r("fix_missing")
devtools::document()
usethis::use_test("fix_missing")
devtools::test()
covr::package_coverage()
usethis::use_r("fix_missing_df")
usethis::use_test("fix_missing_df")
devtools::document()
devtools::check()
usethis::use_package("purrr")
usethis::use_pipe(export = FALSE)
